# vscode-kubernetes-tools: exclude
# (because OpenShift routes seem to be interpreted as pods ¯\_(ツ)_/¯)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: deploy-sa-notfound
  labels:
    app: deploy-sa-notfound
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: deploy-sa-notfound
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-sa-notfound
  labels:
    app: deploy-sa-notfound
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: deploy-sa-notfound
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sa-notfound
  labels:
    app: deploy-sa-notfound
spec:
  selector:
    matchLabels:
      app: deploy-sa-notfound
  template:
    metadata:
      labels:
        app: deploy-sa-notfound
    spec:
      replicas: 1
      containers:
      - name: default
        image: caddy:2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: caddy-config
          mountPath: "/etc/caddy"
        - name: caddy-config-cache
          mountPath: "/config/caddy"
      securityContext:
        runAsUser: 1003870000
      serviceAccount: deploy-sa-notfound # ServiceAccount does not exist (by default, only `default` exists)
      serviceAccountName: deploy-sa-notfound 
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config-port-8080
      - name: caddy-config-cache
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config-port-8080
  labels:
    app: unknown-configmap
data:
  Caddyfile: |-
    http://:8080

    respond "Hello, world!"
      