name: ci-build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
   

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17,1.18,1.19]
    name: Build and Test with Go ${{ matrix.go-version }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make test-with-coverage

    - name: Codecov
      if: ${{ matrix.go-version }} == '1.17'
      uses: codecov/codecov-action@v3.1.1
      with:
        # Path to coverage file to upload
        file: coverprofile.out

  golangci:
    name: Lint with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint
      uses: golangci/golangci-lint-action@v3.3.0
      with:
        version: latest
        args: -c .golangci.yml